# fly.toml app configuration file generated for animegarden-production on 2024-09-20T21:22:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animegarden-production'
primary_region = 'hkg'

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "node packages/app/dist/server/entry.mjs"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = "on-failure"
  retries = 10
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
