app = 'animegarden-server-test'
primary_region = 'hkg'

[build]
  dockerfile = 'Dockerfile'

[processes]
  server = 'node apps/backend/manager/cli.mjs --cron'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['server']

[[restart]]
  policy = 'on-failure'
  retries = 10
  processes = ['server']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
