# fly.toml app configuration file generated for animegarden-server-test on 2025-01-04T19:09:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animegarden-web-test'
primary_region = 'hkg'

[build]
dockerfile = 'Dockerfile'

[build.args]
NODE_VERSION = '20.10.0'
PNPM_VERSION = '10.4.1'
APP_HOST = 'test.animes.garden'
SERVER_URL = 'http://animegarden-server-test.internal:3000/'

[processes]
server = 'node apps/frontend/web/server.mjs'

[http_service]
internal_port = 3000
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 0
processes = ['server']

# [[restart]]
#   policy = 'on-failure'
#   retries = 10
#   processes = ['server', 'cron']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
