# fly.toml app configuration file generated for animegarden-web-production on 2025-04-09T22:04:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animegarden-web-production'
primary_region = 'lax'

[build]
dockerfile = 'Dockerfile'

[build.args]
NODE_VERSION = '20.19.0'
PNPM_VERSION = '10.8.0'
APP_HOST = 'animes.garden'
FEED_HOST = 'api.animes.garden'
SERVER_URL = 'http://animegarden-server-production.internal:3000/'
UMAMI_ID = 'bcff225d-6590-498e-9b39-3a5fc5c2b4d1'

[processes]
server = 'node apps/frontend/web/server.mjs'

[http_service]
internal_port = 3000
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1
processes = ['server']

# [[restart]]
#   policy = 'on-failure'
#   retries = 10
#   processes = ['server', 'cron']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
