# fly.toml app configuration file generated for animegarden-server-production on 2024-09-21T23:49:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animegarden-server-production'
primary_region = 'hkg'

[build]
  dockerfile = 'Dockerfile'

[processes]
  server = 'node packages/server/dist/index.mjs'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['server']

[[restart]]
  policy = 'on-failure'
  retries = 10
  processes = ['server']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
