name: Deploy Fly

on:
  workflow_dispatch:

jobs:
  web:
    name: Deploy Web

    runs-on: ubuntu-latest

    concurrency: deploy-fly-web-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --config ./apps/frontend/web/fly.toml \
            --app animegarden-web-test --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  server:
    name: Deploy Server

    runs-on: ubuntu-latest

    concurrency: deploy-fly-server-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --config ./apps/backend/manager/fly.toml \
            --app animegarden-server-test --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
