name: Deploy Fly

on:
  workflow_dispatch:

jobs:
  app:
    name: Deploy app

    runs-on: ubuntu-latest

    concurrency: deploy-fly-app-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config ./packages/app/fly.toml --app animegarden-app-test --remote-only --build-secret SERVER_HOST=animegarden-server-production.internal --build-secret APP_HOST=garden.breadio.wiki
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  server:
    name: Deploy server

    runs-on: ubuntu-latest

    concurrency: deploy-fly-server-group

    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config ./apps/backend/manager/fly.toml --app animegarden-server-test --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
